import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Tab, TabGroup, TabList, TabPanel, TabPanels } from "@headlessui/react";
import { getDisplayName } from "next/dist/shared/lib/utils";

const tabs = [
  {
    key: "all",
    display: "All",
    // href: "#",
    // current: true,
  },
  {
    key: "mountains",
    display: "Mountains",
    // href: "#",
    // current: false,
  },
  {
    key: "other",
    display: "Other",
    // href: "#",
    // current: false,
  },
]

export default function Home() {
  return (
    <div className="flex flex-col h-full bg-neutral-50">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <header className="flex justify-between items-center h-[90px] px-6">
        <div className="text-center">david lennström</div>
        <Link
          href="#"
          className="rounded-3xl bg-neutral-200 px-3 py-2 hover:bg-opacity-80"
        >
          Contact
        </Link>
      </header>
      <main className="grow">
        <div className="flex flex-col items-center h-full">
          <TabGroup>
            <TabList className="flex items-center gap-12">
              {tabs.map((tab) => (
                    <Tab key={tab.key} className="p-2">
                    {({ selected }) => (
                      <span
                        className={selected ? "text-black" : "text-neutral-500"}
                      >
                        {tab.display}
                      </span>
                    )}
                  </Tab>
              ))}
            </TabList>
            <TabPanels className="h-full w-full bg-neutral-200 max-w-[900px] p-2 sm:p-4 my-6">
              <TabPanel>All Photos</TabPanel>
              <TabPanel>Mountains</TabPanel>
              <TabPanel>Other</TabPanel>
            </TabPanels>
          </TabGroup>
        </div>
      </main>
      <footer className="h-[60px] flex justify-center items-center">
        <p>david lennström</p>
      </footer>
    </div>
  );
}
