import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
   <div>
    <Head>
      <title>Home</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="./favicon.ico" />
    </Head>
    <main className="text-red-500">
    <p>Placeholder</p>

    </main>
    <footer>
    <p>Placeholder for footer</p>
    </footer>
    </div>
  );
}
